// gifoogle-vue/src/components/Random.vue
<template>
  <div>
    <img
      :src="fullUrl"
      width="100%"
    />
  </div>
</template>
<script>
import { mapGetters } from 'vuex';
import * as Util from "../utils";
export default {
  name: 'Random',
  computed: {
    ...mapGetters({
      randomGif: `randomGif`
    }),
    ...{
      fullUrl() {
        return Util.getFullUrl(this.randomGif.id)
      }
    }
  }
};
</script>

<style lang="scss"></style>

// gifoogle-angular/src/app/pages/random/random.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from "src/app/services/data.service";
import * as Util from "src/app/utils";

@Component({
  selector: 'app-random',
  templateUrl: './random.component.html',
  styleUrls: ['./random.component.scss']
})
export class RandomComponent implements OnInit {
  randomGif: Object = {};

  constructor(private data: DataService) {}

  ngOnInit() {
    this.data.getRandomGif().subscribe(res => {
      this.randomGif = res;
    });
  }

  getFullUrl(gifId) {
    return Util.getFullUrl(gifId);
  };
}

<div>
  <img
    [src]="getFullUrl(randomGif?.data?.id)"
    width="100%"
  />
</div>
