// gifoogle-vue/src/views/CardColumns.vue
<template>
  <div class="card-columns" style="column-count: 4">
    <div
      class="card"
      v-for="obj in gifs"
      :key="obj.id"
      style="width: 270px; border: none;"
    >
      <img
        :src="`https://media.giphy.com/media/${obj.id}/giphy.gif`"
        width="270px"
      />
    </div>
  </div>
</template>

<script>
export default {
  name: 'CardColumns',
  props: {
    gifs: {
      type: Array,
      required: true
    }
  }
};
</script>

// gifoogle-react/src/components/CardColumns.js
import React from "react";

const CardColumns = props => {
  const { gifs = [] } = props;
  return (
    <div className="card-columns" style={{columnCount: 4}}>
      {gifs.map(obj => {
        return (
          <div
            className="card"
            key={obj.id}
            style={{ width: '270px', border: 'none'}}
          >
            <img
              src={`https://media.giphy.com/media/${obj.id}/giphy.gif`}
              width="270px"
              alt="gif"
            />
          </div>
        );
      })}
    </div>
  );
};

export default CardColumns;
