// gifoogle-angular/src/app/components/card-columns/card-columns.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-card-columns',
  templateUrl: './card-columns.component.html',
  styleUrls: ['./card-columns.component.scss']
})
export class CardColumnsComponent implements OnInit {

  @Input() gifs: any;

  constructor() { }

  ngOnInit() {
  }

  getFullUrl = gifId => {
    return `https://media.giphy.com/media/${gifId}/giphy.gif`;
  };

}

<div class="card-columns">
  <div class="card" *ngFor="let obj of gifs">
    <img [src]="getFullUrl(obj.id)" width="263px" />
  </div>
</div>

// gifoogle-react/src/components/CardColumns.js
import React from "react";

const CardColumns = props => {
  const { gifs = [] } = props;
  return (
    <div className="card-columns" style={{columnCount: 4}}>
      {gifs.map(obj => {
        return (
          <div
            className="card"
            key={obj.id}
            style={{ width: '270px', border: 'none'}}
          >
            <img
              src={`https://media.giphy.com/media/${obj.id}/giphy.gif`}
              width="270px"
              alt="gif"
            />
          </div>
        );
      })}
    </div>
  );
};

export default CardColumns;
