// gifoogle-react/src/containers/Random.js
import React, { Component } from "react";
import { connect } from "react-redux";

class Random extends Component {
  render() {
    const { randomGif = {} } = this.props;
    return (
      <div>
        <img
          src={`https://media.giphy.com/media/${randomGif.id}/giphy.gif`}
          width="100%"
          alt="gif here"
        />
      </div>
    );
  }
}

const mapStateToProps = state => {
  return {
    randomGif: state.gifs.randomGif
  };
};

export default connect(mapStateToProps)(Random);

// gifoogle-vue/src/components/Random.vue
<template>
  <div>
    <img
      :src="`https://media.giphy.com/media/${randomGif.id}/giphy.gif`"
      width="100%"
    />
  </div>
</template>
<script>
import { mapGetters } from 'vuex';
export default {
  name: 'Trending',
  computed: {
    ...mapGetters({
      randomGif: `randomGif`
    })
  }
};
</script>

<style lang="scss"></style>
