// gifoogle-angular/src/app/components/search-bar/search-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from "src/app/services/data.service";

@Component({
  selector: 'app-search-bar',
  templateUrl: './search-bar.component.html',
  styleUrls: ['./search-bar.component.scss']
})
export class SearchBarComponent implements OnInit {
  query: string = '';

  constructor(private data: DataService) { }

  ngOnInit() {
  }

  onSubmit(event) {
    event.preventDefault();
    this.data.getGifsByQuery(this.query);
  }
}

<form (submit)="onSubmit($event)">
  <h5>Search all GIPHY GIFs</h5>
  <div class="form-group">
    <input name="query-input" class="form-control" [(ngModel)]="query" />
    <button class="btn btn-primary" type="submit">Search</button>
  </div>
</form>

// gifoogle-vue/src/components/SearchBar.vue
<template>
  <form @submit.prevent="onSubmit">
    <h5>Search all GIPHY GIFs</h5>
    <div class="form-group">
      <input class="form-control" v-model="query" />
      <button class="btn btn-primary" type="submit">Search</button>
    </div>
  </form>
</template>

<script>
export default {
  name: 'SearchBar',
  data() {
    return {
      query: ''
    };
  },
  methods: {
    onSubmit() {
      this.$store.dispatch('getGifsByQuery', this.query);
    }
  }
};
</script>

<style lang="scss" scoped>
.form-group {
  display: flex;
  input {
    border-radius: 0;
  }
  button {
    border-radius: 0;
  }
}
</style>
