// gifoogle-react/src/containers/SearchBar.js
import React, { Component } from "react";
import { connect } from "react-redux";
import { getGifsByQuery } from "../_store/actions";

class SearchBar extends Component {
  constructor(props) {
    super(props);
    this.state = {
      query: ""
    };
  }

  onSearch = event => {
    event.preventDefault();
    this.props.getGifs(this.state.query);
  };

  onQueryChange = event => {
    this.setState({
      query: event.target.value
    });
  };

  render() {
    const { query } = this.state;
    return (
      <form onSubmit={this.onSearch} className="search-form">
        <h5>Search all GIPHY GIFs</h5>
        <div className="form-group">
          <input
            className="form-control"
            value={query}
            onChange={this.onQueryChange}
          />
          <button className="btn btn-primary" type="submit">
            Search
          </button>
        </div>
      </form>
    );
  }
}

const mapStateToProps = state => {
  return {};
};

const mapDispatchToProps = dispatch => {
  return {
    getGifs: query => dispatch(getGifsByQuery(query))
  };
};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(SearchBar);

// gifoogle-vue/src/components/SearchBar.vue
<template>
  <form @submit.prevent="onSubmit">
    <h5>Search all GIPHY GIFs</h5>
    <div class="form-group">
      <input class="form-control" v-model="query" />
      <button class="btn btn-primary" type="submit">Search</button>
    </div>
  </form>
</template>

<script>
export default {
  name: 'SearchBar',
  data() {
    return {
      query: ''
    };
  },
  methods: {
    onSubmit() {
      this.$store.dispatch('getGifsByQuery', this.query);
    }
  }
};
</script>

<style lang="scss" scoped>
.form-group {
  display: flex;
  input {
    border-radius: 0;
  }
  button {
    border-radius: 0;
  }
}
</style>
