// gifoogle-vue/src/components/Home.vue
<template>
  <div>
    <search-bar />
    <card-columns :gifs="searchGifs" />
  </div>
</template>

<script>
import { mapGetters } from 'vuex';
import SearchBar from './SearchBar';
import CardColumns from '../views/CardColumns';
export default {
  name: 'Home',
  components: {
    SearchBar,
    CardColumns
  },
  computed: {
    ...mapGetters({
      searchGifs: `searchGifs`
    })
  }
};
</script>

// gifoogle-react/src/containers/Home.js
import React, { Component } from "react";
import { connect } from "react-redux";
import SearchBar from "./SearchBar";
import CardColumns from "../components/CardColumns";

class Home extends Component {
  render() {
    const { searchGifs = [] } = this.props;
    return (
      <div>
        <SearchBar />
        <CardColumns gifs={searchGifs} />
      </div>
    );
  }
}

const mapStateToProps = state => {
  return {
    searchGifs: state.gifs.searchGifs
  };
};

export default connect(mapStateToProps)(Home);
