// gifoogle-vue/src/components/Trending.vue
<template>
  <card-columns :gifs="trendingGifs" />
</template>
<script>
import { mapGetters } from 'vuex';
import CardColumns from '../views/CardColumns';
export default {
  name: 'Trending',
  components: {
    CardColumns
  },
  computed: {
    ...mapGetters({
      trendingGifs: `trendingGifs`
    })
  }
};
</script>

<style lang="scss"></style>

// gifoogle-react/src/containers/Trending.js
import React, { Component } from "react";
import { connect } from "react-redux";
import CardColumns from "../components/CardColumns";

class Trending extends Component {
  render() {
    const { trendingGifs = [] } = this.props;
    return (
      <CardColumns gifs={trendingGifs}/>
    );
  }
}

const mapStateToProps = state => {
  return {
    trendingGifs: state.gifs.trendingGifs
  };
};

export default connect(mapStateToProps)(Trending);
